# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0']

    steps:
    - uses: actions/checkout@v2
#    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
 #     uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
  #    with:
   #     ruby-version: ${{ matrix.ruby-version }}
    #    bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    #- name: Run tests
     # run: bundle exec rake
      

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install snyk -g # install snyk
    - run: npm instal snyk-to-html
    - run: snyk -v
    - run: snyk auth ${{ secrets.SNYK_TOKEN }} # snyk authentication using GH secrets

    - name: Bash for GitHub Actions
      run: chmod +x ./snyk-scan.sh --mode=monitor --html=1 --type=all --org=monorepo-org
